---
- name: Install Apache and Upload my Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:

  - name: Check and Print LINUX Version
    debug: var=ansible_os_family


  - block:   # REDHAT
      
    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest

    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache RedHat

    - name: Start WebServer and make it enable on boot for RedHat
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:   # Debian

    - name: Install Apache Web Server for Debian
      apt: name=apache2 state=latest
    
    - name: Copy MyHomePage to Servers
      copy: src={{ source_file }} dest={{ destin_file }} mode=0555
      notify: Restart Apache Debian

    - name: Start WebServer and make it enable on boot for Debian
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    servoce: name=apache2 state=restarted