---
- name : My Playbook for Variables Lesson
  hosts: all
  become: yes

  vars:
    message1: Privet
    message2: World
    secret: awdh1d231f21e312d122

  tasks:

  - name: Print Secret variable
    debug:
      var: secret

  - debug:
      msg: "Secret word: {{ secret }}"

  - debug:
      msg: "Owner for server --> {{owner}} <--"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"
  
  - debug:
      var: full_message

  - debug:
      var: ansible_distribution

  - shell: uptime
    register: results

  - debug:
      var: results.stdout